import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
export default defineSchema({
    agents: defineTable({
        id: v.string(),
        name: v.string(),
        projectName: v.string(),
        workspace: v.string(),
        metroServerUrl: v.string(),
        status: v.union(v.literal("done"), v.literal("running"), v.literal("idle"), v.literal("error")),
        parentId: v.optional(v.string()),
        model: v.string(),
        provider: v.string(),
        createdAt: v.number(),
        lastUpdatedAt: v.number(),
    }),
    workspaces: defineTable({
        id: v.string(),
        title: v.string(),
        branch: v.string(),
        baseRef: v.string(),
        baseCommitSha: v.string(),
        status: v.union(v.literal("active"), v.literal("archived")),
        repositoryPath: v.string(),
        repositoryOwner: v.optional(v.string()),
        repositoryName: v.optional(v.string()),
        worktreePath: v.string(),
        path: v.string(),
        tunnelUrl: v.optional(v.string()),
        metroPort: v.optional(v.number()),
        sessionId: v.optional(v.string()),
        tags: v.array(v.string()),
        archived: v.optional(v.boolean()),
        archivedAt: v.optional(v.string()),
        packageManager: v.optional(v.string()),
        createdAt: v.number(),
        lastUpdatedAt: v.number(),
    }).index("by_workspace_id", ["id"]),
});
